language: go

go:
  - master

before_install:
  - go get -u golang.org/x/lint/golint

stages:
  - build

build:hw01:
  stage: build
  script:
  - cd hw01
  - golint -set_exit_status ./...
  - go vet ./...
  - go test ./...
  - go build

build:hw02:
  stage: build
  script:
    - cd hw02
    - golint -set_exit_status ./...
    - go vet ./...
    - go test ./...
    - go build
