language: go

go:
  - master

before_install:
  - go get -u golang.org/x/lint/golint

stages:
  - build

.common_script: &common_script
  - golint -set_exit_status ./...
  - go vet ./...
  - go test ./...
  - go build

jobs:
  include:
    - stage: build
      script:
      - cd hw01
      - *common_script

    - stage: build
      script:
        - cd hw02
        - *common_script

    - stage: build
      script:
        - cd hw03
        - *common_script

    - stage: build
      script:
        - cd hw04
        - *common_script

    - stage: build
      script:
        - cd hw05
        - *common_script

    - stage: build
      script:
        - cd hw06
        - *common_script

    - stage: build
      script:
        - cd hw07
        - *common_script

    - stage: build
      script:
        - cd calendar
        - *common_script