language: go

go:
  - master

before_install:
  - go get -u golang.org/x/lint/golint

stages:
  - build

jobs:
  include:
    - stage: build
      script:
      - cd hw01
      - golint -set_exit_status ./...
      - go vet ./...
      - go test ./...
      - go build

    - stage: build
      script:
        - cd hw02
        - golint -set_exit_status ./...
        - go vet ./...
        - go test ./...
        - go build

    - stage: build
      script:
        - cd hw03
        - golint -set_exit_status ./...
        - go vet ./...
        - go test ./...
        - go build

    - stage: build
      script:
        - cd hw04
        - golint -set_exit_status ./...
        - go vet ./...
        - go test ./...
        - go build

    - stage: build
      script:
        - cd hw05
        - golint -set_exit_status ./...
        - go vet ./...
        - go test ./...
        - go build
