language: go

go:
  - master

before_install:
  - go get -u golang.org/x/lint/golint

stages:
  - build_hw01
  - build_hw02
  - build_hw03

jobs:
  include:
    - stage: build_hw01
      script:
      - cd hw01
      - golint -set_exit_status ./...
      - go vet ./...
      - go test ./...
      - go build

    - stage: build_hw02
      script:
        - cd hw02
        - golint -set_exit_status ./...
        - go vet ./...
        - go test ./...
        - go build

    - stage: build_hw03
      script:
        - cd hw03
        - golint -set_exit_status ./...
        - go vet ./...
        - go test ./...
        - go build
