// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/AndreyAndreevich/otus_go/calendar/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Delivery is an autogenerated mock type for the Delivery type
type Delivery struct {
	mock.Mock
}

// AddHandler provides a mock function with given fields: pattern, handler
func (_m *Delivery) AddHandler(pattern string, handler domain.Handler) {
	_m.Called(pattern, handler)
}

// Run provides a mock function with given fields: ctx
func (_m *Delivery) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
