// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/AndreyAndreevich/otus_go/calendar/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Producer is an autogenerated mock type for the Producer type
type Publisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: event
func (_m *Publisher) Publish(event domain.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
